import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// import pkjSlide from './docs/packages/sidebar.json';
// import AQSlide from './docs/a&q/sidebar.json';
// import cmpSlide from './docs/components/sidebar.json';
// import utilsSlide from './docs/utils/sidebar.json';

type SidebarConfig = SidebarsConfig[string];

const sidebars: SidebarsConfig = {
  // packages: pkjSlide as SidebarConfig,
  // components: cmpSlide as SidebarConfig,
  // utils: utilsSlide as SidebarConfig,
  // "a&q": AQSlide as SidebarConfig,
  componentsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;